### ISSUE TITLE
ttk.Frame and ttk.LabelFrame resize

### ISSUE THREAD

**Issue by dgdav99** [alejandroautalan/pygubu#113]
_A Python script built with Tkinter to help Python devs to build Tkinter GUIs, great idea!_
However, I noticed that sometimes ttk frames and ttk labelframes (just tested these, don't know if this happens with other widgets too) tend to assume the size (width+height) of the widget(s) contained inside them, even if I declare a specific (bigger) size in their own properties. Is this wanted or is it a bug?

_New to Python and Tkinter here but loving Pygubu (even if I usually prefer to code everything by myself to have control over everything)._

**Comment by alejandroautalan** [comment]
Hello dgdav99, thanks for trying pygubu. And sorry for the late response.

Yes, that is the default behavior for almost all widgets.
Since pygubu uses the grid layout management, you can alter this behavior for a specific widget changing the **propagate** property to **false** (Layout Tab > Grid options > propagate).

See a better explanation of the grid_propagate method here (http://infohost.nmt.edu/%7Eshipman/soft/tkinter/web/grid-methods.html)

Regards
Alejandro A,

**Comment by dgdav99** [comment]
Thanks for your explanation
I didn't knew about that property, sorry :/

Are there any plans to implement the place method alongside with grid?

Davide

**Comment by alejandroautalan** [comment]
Hi, Dadive

> Thanks for your explanation
> I didn't knew about that property, sorry :/

 You're welcome.

> Are there any plans to implement the place method alongside with grid?

Right now I have no plans to implement it, maybe in the future.

Regards.
Alejandro A.
