### ISSUE TITLE
Fail to bring up pygubu 0.9.8.1 under Windows when installed using setup.py

### ISSUE THREAD

**Issue by jfongattw** [alejandroautalan/pygubu#124]
I had download pygubu from pypi and install it using "python setup.py install". The installation seems fine which I had check through "import pygubu". But nothing happens after executing "pygubu-designer.exe"
I had try this on both WinXP and Win7, the same result.

After uninstall it, I changed the way of install by using "pip install pygubu" online. Now it works on both Windows.

Best Regards,
Jach Fong

**Comment by edmundackah** [comment]
Same here when i run "pygubu-designer.exe" nothing happens. Could someone make a video on pygubu installation for windows, am a complete novice at this.

**Comment by alejandroautalan** [comment]
Hi edmundackah, thanks for trying pygubu and sorry for the late response.

Try this, install the module **appdirs** using pip (or other method):

    pip install appdirs

Appdirs module is not installed automatically when using setup.py.
However, when pygubu-designer starts, a message should be displayed informing about the missing dependency.
I think that the message is not shown in windows since pygubu started using "entry points" #66. I will continue looking for a solution for this.

Let me know if installing the dependency works.
Regards,
Alejandro A.

**Comment by edmundackah** [comment]
Thank you for the help, it's working now

**Comment by YourHuckleberry** [comment]
Same issue, Windows 10 and there was no message displayed.  Installing appdirs resolved the problem.

**Comment by jawad427** [comment]
How to open pygubu designer .
I cant find it in c

**Comment by alejandroautalan** [comment]
Hello jawad427, thanks for trying pygubu.

> How to open pygubu designer .
> I cant find it in c

To use the designer you need to install pygubu-designer. Since version 0.10 the project was splitted in two parts, see the README file.

Regards
Alejandro A.
