### ISSUE TITLE
How pass arguments to custom class?

### ISSUE THREAD

**Issue by anshibanov** [alejandroautalan/pygubu#203]
@alejandroautalan big thanks for this example: https://github.com/alejandroautalan/pygubu/issues/196#issuecomment-632981659 
But i don't understand how i can pass arguments in DateEntry class? I want make something like this
`DateEntry(top, width=12, background='darkblue',foreground='white', borderwidth=2, year=2010)`

**Comment by anshibanov** [comment]
@alejandroautalan gelp?please (

**Comment by alejandroautalan** [comment]
Hello anshibanov, thanks for trying pygubu and sorry for the late response.
I am working for a complete answer here https://github.com/alejandroautalan/pygubu/wiki/IncorporateCustomWidget-Example2.
Its not complete yet because the last part will require and update to the pygubu code.
Please wait a little more until tomorrow nigth.

Regards.
Alejandro A.

**Comment by anshibanov** [comment]
@alejandroautalan  
Big thank for attention and for pygubu
My question still in progress?

I about "Option 3 - Widget specific options"
