### ISSUE TITLE
Add tk.OptionMenu to "Control&Display" in tk widgets

### ISSUE THREAD

**Issue by alejandroautalan** [alejandroautalan/pygubu#237]
User request:

> If so, can I suggest adding the tk.OptionMenu to the existing list of Control&Display in tk widgets?
> Of course the ttk.Combobox is equivalent, but just in case people prefer the visual look of the OptionMenu over other widgets.

**Comment by rdbende** [comment]
> Of course the ttk.Combobox is equivalent,

`OptionMenu` and `Combobox` aren't equivalent! `OptionMenu` is a button with a dropdown menu, that from the user can select values with radiobuttons. `Combobox` on the other hand is an *Entry* with a dropdown, the user can type in values (if not readonly), the dropdown is scrollable, and it's not a menu, it doesn't use radiobuttons to select.

> but just in case people prefer the visual look of the OptionMenu over other widgets.

I think people don't like the visual look of `OptionMenu`, `Combobox` is so much nicer. But I think `OptionMenu` must be added so that the user can decide which one is needed.
