### ISSUE TITLE
error - from appdirs import AppDirs ImportError: No module named 'appdirs

### ISSUE THREAD

**Issue by teaddict** [alejandroautalan/pygubu#52]
if you have got this “from appdirs import AppDirs ImportError: No module named 'appdirs'” error after installing pygubu, you should install “Determining appropriate platform-specific directories” from ubuntu software center.

**Comment by ADavidLiu** [comment]
What about Windows 10?

**Comment by alejandroautalan** [comment]
Hello, thanks for trying pygubu.

If you are using python3, try this command in the console:

```
pip3 install appdirs
```

Regards,
Alejandro A.

**Comment by ADavidLiu** [comment]
Hello, Thank you for replying.

I'm executing that command from the Python Command Line console but I'm getting the error: SyntaxError: invalid syntax.

**Comment by xenatisch** [comment]
Hi @ADavidLiu 

Maybe try this line instead:

> python3 -m pip install appdirs

If the problem persists, it's because your Python does not have an alias in your command prompt. Find out what is the directory of your python executable. Once you do that, the command would look something like this:

> c:\path_to\python\versions\3.5\python3 -m pip install appdirs 

Have a go and let's see if it works.
Best,
-Pouria
